# Generated by Django 3.2 on 2025-02-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinter_app', '0003_sprint_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
