# Generated by Django 3.2 on 2025-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinter_app', '0005_task_storypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='s3_folder',
            field=models.CharField(default='', max_length=255),
        ),
    ]
