# Generated by Django 3.2 on 2025-03-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinter_app', '0006_sprint_s3_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
