# Generated by Django 3.2 on 2025-03-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprinter_app', '0007_sprint_isarchived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='isArchived',
            new_name='is_archived',
        ),
    ]
